Fix StateManager reload error - remove non-existent method call
Fixed error: 'StateManager' object has no attribute 'reload'

Removed state_manager.reload() call since StateManager doesn't
have this method. New images are automatically discovered when
/api/images endpoint scans the image directory.